name: electron-build-pr

on:
  pull_request:
    branches:
    - master

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: Build the site
      run: |
        npm install -g yarn
        yarn install
        yarn build

  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: Build the site
      run: |
        npm install -g yarn
        yarn install
        yarn build

  build_on_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: Build the site
      run: |
        npm install -g yarn
        yarn install
        yarn build

