name: web-build-master

on:
  push:
    branches:
    - master

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: see directory
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build

